### PR TITLE
Payment with Stripe 

### PR DESCRIPTION
**Pull request by SophieSjoberg**
## Description 
Implement Stripe form for order payments/transactions 

## Screenshot 

stripe payment form

### CODE REVIEW

**Review by tochman — APPROVED** [review]
It looks good to me but I've worked on this one so I should not be the one who merges it. 

Also, I'm ready to answer questions about the refactorings I did to the JS files and the way we load maps and geocode.

**Review by lcegit — COMMENTED** [review]
Looks great! Thanks for the walkthrough.

**Review by tochman — COMMENTED** [review]
Hmm... there ware some comments and console.log statements that could have been removed before merge. Please make sure to make thorough reviews of each others PR's

**Comment by lcegit** [comment]
Sure. We understand that these type of comments cannot be included in a deployed app. In this case we'd prefer to keep these comments for future reference. Note taken though.

**Pull request merged**
