### PR TITLE
[Chore] Clean up code

### PR DESCRIPTION
**Pull request by NegativeKarma**
# PT-link: https://www.pivotaltracker.com/story/show/154394431

### CODE REVIEW

**Review by SophieSjoberg — COMMENTED** [review]
Thank you for doing this Francesco 👍  Wondering why you change double quotes to single in step defs? Cucumber generates them as doubles.

**Comment by NegativeKarma** [comment]
It's beautify. It definitely looks better but I think it does that also because it's standard not to use double quotes there

**Review by tochman — DISMISSED** [review]
Great job!!! I like the cleaning

**Comment by tochman** [comment]
Well, the tests are failing so there's a few more cleanings to do ;- )

**Review by lcegit — APPROVED** [review]
Code looks nicely formatted 💯

**Pull request merged**
