### PR TITLE
User can register on mobile app

### PR DESCRIPTION
**Pull request by NegativeKarma**
# PT-link: https://www.pivotaltracker.com/story/show/154561994

## Description:
Authenticate users via API with Devise auth token

## What we learned:
* How to set up Devise auth token gem and create unit tests for it
* A better understanding of controllers inherit system and of controllers related to the API
* How to edit and rename a migration file properly

## Screenshot:
screen shot 2018-01-24 at 19 49 12

### CODE REVIEW

**Review by diraulo — DISMISSED** [review]
Looks good

**Comment by diraulo** [comment]
The code looks good. Fix the merge issue with `Gemfile` and we can get this in

**Comment by NegativeKarma** [comment]
Will do

**Review by SophieSjoberg — APPROVED** [review]
LGTM 👍

**Pull request merged**
